from growatt_dbus_config import DEVICE_INSTANCE, HOST, PORT, REG_POWER_LIMIT_TOTAL, UNIT_ID
from modbus_types import MB_INPUT_BINARY, MB_HOLDING_REGISTER, MB_INPUT_REGISTER, MB_NONE, ON_ERROR_DEFAULT, ON_ERROR_KEEP

REG = [
    # Settings / local DBus-only values
    {
        "name": "custom_name",
        "path": "/CustomName",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": "",
        "on_error": ON_ERROR_KEEP,
        "setting": "",
        "setting_path": f"/Settings/Devices/Ecoforest{DEVICE_INSTANCE}/CustomName",
        "writeable": True,
    },
    {
        "name": "position",
        "path": "/Position",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": 1,
        "on_error": ON_ERROR_KEEP,
        "setting": 1,
        "setting_path": f"/Settings/Devices/Ecoforest{DEVICE_INSTANCE}/Position",
        "setting_min": 0,
        "setting_max": 2,
        "writeable": True,
        "cast": int,
    },

    # Static product / management information
    {
        "name": "process_name",
        "path": "/Mgmt/ProcessName",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": "string",
        "default": __file__,
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "process_version",
        "path": "/Mgmt/ProcessVersion",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": "string",
        "default": "1.1",
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "connection",
        "path": "/Mgmt/Connection",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": "string",
        "default": f"Modbus TCP {HOST}:{PORT}, unit {UNIT_ID}",
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "product_name",
        "path": "/ProductName",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": "Ecoforest Heat Pump",
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "product_id",
        "path": "/ProductId",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": 0000,
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "deviceinstance",
        "path": "/DeviceInstance",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": "u32",
        "default": DEVICE_INSTANCE,
        "on_error": ON_ERROR_KEEP,
    },

    # Device information
    {
        "name": "firmware_version",
        "path": "/FirmwareVersion",
        "address": 9,
        "length": 3,
        "regtype": MB_NONE,
        "encoding": "ascii",
        "default": "0.0.0",
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "hardware_version",
        "path": "/HardwareVersion",
        "address": 12,
        "length": 3,
        "regtype": MB_NONE,
        "encoding": "ascii",
        "default": "0.0.0",
        "on_error": ON_ERROR_KEEP,
    },

    # Status
    {
        "name": "status",
        "path": "/StatusCode",
        "address": 50,
        "length": 1,
        "regtype": MB_INPUT_BINARY,
        "default": 0,
        "on_error": ON_ERROR_KEEP,
        "map": {0: 1, 1: 0},
    },
    {
        "name": "temperature",
        "path": "/Temperature",
        "address": 17,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "i16",
        "default": 0.0,
        "on_error": ON_ERROR_KEEP,
        "scale": 10.0,
    },
    {
        "name": "targettemperature",
        "path": "/TargetTemperature",
        "address": 134,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u16",
        "default": 0.0,
        "on_error": ON_ERROR_KEEP,
        "scale": 10.0,
    },

    # AC total
    {
        "name": "ac_power_total",
        "path": "/Ac/Power",
        "address": 5082,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "i16",
        "default": 0.0,
        "on_error": ON_ERROR_KEEP,
        "scale": 1,
    },
    {
        "name": "total_energy",
        "path": "/Ac/Energy/Forward",
        "address": 5168,
        "length": 12,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "sum_u16",
        "default": 0.0,
        "on_error": ON_ERROR_KEEP,
        "scale": 1.0,
    },
]
