from config import DEVICE_INSTANCE, HOST, PORT, REG_POWER_LIMIT_TOTAL, UNIT_ID
from modbus_types import MB_HOLDING_REGISTER, MB_INPUT_REGISTER, MB_NONE, ON_ERROR_DEFAULT, ON_ERROR_KEEP

REG = [
    # Settings / local DBus-only values
    {
        "name": "custom_name",
        "path": "/CustomName",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": "",
        "on_error": ON_ERROR_KEEP,
        "setting": "",
        "setting_path": "/Settings/Devices/Growatt/CustomName",
        "writeable": True,
    },
    {
        "name": "position",
        "path": "/Position",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": 1,
        "on_error": ON_ERROR_KEEP,
        "setting": 1,
        "setting_path": "/Settings/Devices/Growatt/Position",
        "setting_min": 0,
        "setting_max": 2,
        "writeable": True,
        "cast": int,
    },

    # Static product / management information
    {
        "name": "process_name",
        "path": "/Mgmt/ProcessName",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": "string",
        "default": __file__,
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "process_version",
        "path": "/Mgmt/ProcessVersion",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": "string",
        "default": "1.1",
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "connection",
        "path": "/Mgmt/Connection",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": "string",
        "default": f"Modbus TCP {HOST}:{PORT}, unit {UNIT_ID}",
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "ac_number_of_phases",
        "path": "/Ac/NumberOfPhases",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": 3,
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "data_manager_version",
        "path": "/DataManagerVersion",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": "1.2.3.4.5.6",
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "fronius_device_type",
        "path": "/FroniusDeviceType",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": 73,
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "limiter_model",
        "path": "/Info/LimiterModel",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": 123,
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "measurement_model",
        "path": "/Info/MeasurementModel",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": 113,
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "is_generic_energy_meter",
        "path": "/IsGenericEnergyMeter",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": 0,
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "product_name",
        "path": "/ProductName",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": "Growatt 3-Phase Inverter",
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "product_id",
        "path": "/ProductId",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": None,
        "default": 41282,
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "deviceinstance",
        "path": "/DeviceInstance",
        "address": None,
        "length": 0,
        "regtype": MB_NONE,
        "encoding": "u32",
        "default": DEVICE_INSTANCE,
        "on_error": ON_ERROR_KEEP,
    },

    # Device information
    {
        "name": "firmware_version",
        "path": "/FirmwareVersion",
        "address": 9,
        "length": 3,
        "regtype": MB_HOLDING_REGISTER,
        "encoding": "ascii",
        "default": "",
        "on_error": ON_ERROR_KEEP,
    },
    {
        "name": "hardware_version",
        "path": "/HardwareVersion",
        "address": 12,
        "length": 3,
        "regtype": MB_HOLDING_REGISTER,
        "encoding": "ascii",
        "default": "",
        "on_error": ON_ERROR_KEEP,
    },

    # Status
    {
        "name": "status_raw",
        "path": "/StatusCode",
        "address": 0,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0,
        "on_error": ON_ERROR_DEFAULT,
        "map": {0: 0, 1: 7, 3: 10},
    },
    {
        "name": "errorcode",
        "path": "/ErrorCode",
        "address": 105,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0,
        "on_error": ON_ERROR_DEFAULT,
    },

    # PV input 1
    {
        "name": "pv1_voltage",
        "path": "/Dc/0/Voltage",
        "address": 3,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "pv1_current",
        "path": "/Dc/0/Current",
        "address": 4,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "pv1_power",
        "path": "/Dc/0/Power",
        "address": 5,
        "length": 2,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "s32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },

    # PV input 2
    {
        "name": "pv2_voltage",
        "path": "/Dc/1/Voltage",
        "address": 7,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "pv2_current",
        "path": "/Dc/1/Current",
        "address": 8,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "pv2_power",
        "path": "/Dc/1/Power",
        "address": 9,
        "length": 2,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "s32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },

    # AC total
    {
        "name": "ac_power_total",
        "path": "/Ac/Power",
        "address": 35,
        "length": 2,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "s32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "total_energy",
        "path": "/Ac/Energy/Forward",
        "address": 53,
        "length": 2,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_KEEP,
        "scale": 10.0,
    },
    {
        "name": "maxpower",
        "path": "/Ac/MaxPower",
        "address": 6,
        "length": 2,
        "regtype": MB_HOLDING_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_KEEP,
        "scale": 10.0,
    },

    {
        "name": "power_limit_percent",
        "path": "/Ac/PowerLimit",
        "address": REG_POWER_LIMIT_TOTAL,
        "length": 1,
        "regtype": MB_HOLDING_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_KEEP,
        "internal": True,
    },

    # Grid / phase values used directly or for derived DBus values
    {
        "name": "grid_freq",
        "path": [
            "/Ac/L1/Frequency",
            "/Ac/L2/Frequency",
            "/Ac/L3/Frequency",
        ],
        "address": 37,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 100.0,
    },
    {
        "name": "l1_voltage",
        "path": "/Ac/L1/Voltage",
        "address": 38,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "l1_current",
        "path": "/Ac/L1/Current",
        "address": 39,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "l1_power",
        "path": "/Ac/L1/Power",
        "address": 40,
        "length": 2,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "s32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "l2_voltage",
        "path": "/Ac/L2/Voltage",
        "address": 42,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "l2_current",
        "path": "/Ac/L2/Current",
        "address": 43,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "l2_power",
        "path": "/Ac/L2/Power",
        "address": 44,
        "length": 2,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "s32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "l3_voltage",
        "path": "/Ac/L3/Voltage",
        "address": 46,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "l3_current",
        "path": "/Ac/L3/Current",
        "address": 47,
        "length": 1,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "u32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
    {
        "name": "l3_power",
        "path": "/Ac/L3/Power",
        "address": 48,
        "length": 2,
        "regtype": MB_INPUT_REGISTER,
        "encoding": "s32",
        "default": 0.0,
        "on_error": ON_ERROR_DEFAULT,
        "scale": 10.0,
    },
]
