# dbus-modbus-client configuration
# Example for Peblar EV Charger

[DEFAULT]
loglevel = INFO
pollinterval = 1.0


# ----------------------------
# Peblar EV Charger
# ----------------------------
[peblar_ev_charger]

# Driver class (de Python file die je net gemaakt hebt)
device = PeblarEVCharger

# Modbus TCP
method = tcp

# IP adres van de Peblar
host = 192.168.11.64

# Modbus TCP port
port = 502

# Modbus slave/unit id
unit = 1

# Poll interval (seconds)
interval = 1

# Timeout
timeout = 2

# Dbus instance (EV chargers meestal 40+)
dbus_instance = 40

# Friendly name
name = Peblar Charger